version: '3.8'

services:
  k6:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - ../reports:/app/reports
    environment:
      # Pass these environment variables from the host machine (set by npm scripts)
      # into the k6 container, so the test toolkit can use them.
      - API_TARGET
      - ENV
      - K6_SCRIPT_NAME
