name: K6 Load Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: npm run docker:build

      - name: Run K6 Tests
        run: |
          npm run test:petstore:smoke
          npm run test:petstore:crud
          npm run test:reqres:smoke

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        if: always() # Always upload, even if tests fail
        with:
          name: k6-test-results
          path: reports/ # This directory is created by the test runs if they produce reports
      
      - name: Send email if K6 fails
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465      # <--- Use 465 for SSL
          secure: true          # <--- Make sure this is set to true!
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: chinthalarohitho@gmail.com
          from: chinthalarohitho@gmail.com
          subject: "🚨 K6 Test Failed in K6_project"
          body: |
            Automated notification:
            Your K6 test failed in GitHub Actions.

 
